onlyBuiltDependencies:
  - '@clerk/shared'
  - '@parcel/watcher'
  - '@tsparticles/engine'
  - browser-tabs-lock
  - bufferutil
  - core-js
  - esbuild
  - react-tsparticles
  - sharp
  - tsparticles-engine
  - unrs-resolver
  - utf-8-validate
